### ISSUE TITLE
 pun_admin_manage_extensions_improved style

### ISSUE THREAD

**Issue by KANekT** [punbb/extensions#16]
В мозилле ширина смотрится нормально, но в хроме и IE9 она значительно хуже и не весь текст ссылок виден.

если исправить так то теперь в мозилле ширина большая.
.main-content th {
     padding: .5em 1.3em;
}
# ext-available-list .tc3,
# ext-installed-list .tc3{

```
width: 5em;
text-align: center;
```

}
# ext-available-list .tc1,
# ext-installed-list .tc2{

```
width: 7em;
text-align: center;
```

}
# ext-installed-list .tc1 {

```
width: 10em;
```

}
# ext-available-list .tc2  {

```
width: 10em;
```

}

**Comment by ashcs** [comment]
Fixed on: https://github.com/punbb/extensions/commit/12848cc9f9bedf45ce54cebb7dd09430aacdac8a
