### ISSUE TITLE
"Reinstall" in pun_admin_manage_extensions_improved passes incorrect data to $ext_info

### ISSUE THREAD

**Issue by hklown** [punbb/extensions#9]
When using "Reinstall" with pun_admin_manage_extensions_improved, the extension's install script is run, but the values in $ext_info are for pun_admin_manage_extensions_improved, not the extension you are re-installing.

Note: This is for reinstalling _another_ extension _with_ pun_admin_manage_extensions_improved.

**Comment by ashcs** [comment]
Fixed on: https://github.com/punbb/extensions/commit/e175f157b40c7abea3e58d801f5c60f514678da7
